name: Build and deploy with maven and JFrog CLI

on: [push]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          oidc-provider-name: github-maxenceb

      - name: audit
        run: |
          jf audit

      - name: configure CLI
        run: jf mvn-config --repo-resolve-releases maxenceb-maven-virtual --repo-resolve-snapshots maxenceb-maven-virtual --repo-deploy-releases maxenceb-maven-virtual --repo-deploy-snapshots maxenceb-maven-virtual

      - name: build and publish
        run: |
          jf mvn clean install
          jf rt bce
          jf rt build-add-git

      - name: scan build
        run: |
          jf bs
