name: github_maven_build

on: [push, workflow_dispatch]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          oidc-provider-name: github-maxenceb

      - name: audit
        run: |
          jf audit --watches maxenceb-maven-watch

      - name: configure CLI
        run: jf mvn-config --repo-resolve-releases maxenceb-maven-virtual --repo-resolve-snapshots maxenceb-maven-virtual --repo-deploy-releases maxenceb-maven-virtual --repo-deploy-snapshots maxenceb-maven-virtual

      - name: Curation audit
        run: |
          jf curation-audit

      - name: build and publish
        run: |
          jf mvn clean install
          jf rt bce
          jf rt build-add-git
          jf rt bp

      - name: scan build
        run: |
          jf build-scan ${{ env.JFROG_CLI_BUILD_NAME }} ${{ env.JFROG_CLI_BUILD_NUMBER }} --vuln
